# Generated by Django 5.2.8 on 2026-09-01 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_secure_avatar_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
        migrations.CreateModel(
            name='MfaCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_secret', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_counter', models.BigIntegerField(blank=True, null=True)),
                ('recovery_code_hashes', models.JSONField(blank=True, default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_credential', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اعتبارنامه ورود دومرحله\u200cای',
                'verbose_name_plural': 'اعتبارنامه\u200cهای ورود دومرحله\u200cای',
                'db_table': 'mfa_credentials',
            },
        ),
    ]
