# Generated by Django 5.2.8 on 2025-11-16 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='has_pdf',
            field=models.BooleanField(default=False, verbose_name='نسخه PDF دارد'),
        ),
        migrations.AddField(
            model_name='book',
            name='has_physical',
            field=models.BooleanField(default=False, verbose_name='نسخه فیزیکی دارد'),
        ),
        migrations.AddField(
            model_name='book',
            name='physical_available',
            field=models.IntegerField(default=0, verbose_name='تعداد موجود'),
        ),
        migrations.AddField(
            model_name='book',
            name='physical_count',
            field=models.IntegerField(default=0, verbose_name='تعداد نسخه فیزیکی'),
        ),
        migrations.AddField(
            model_name='book',
            name='physical_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='محل نگهداری'),
        ),
        migrations.CreateModel(
            name='PhysicalBookBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=200, verbose_name='نام امانت\u200cگیرنده')),
                ('borrower_email', models.EmailField(max_length=254, verbose_name='ایمیل امانت\u200cگیرنده')),
                ('borrower_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('borrow_date', models.DateField(verbose_name='تاریخ امانت')),
                ('return_date', models.DateField(verbose_name='تاریخ بازگشت')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='تاریخ واقعی بازگشت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('is_returned', models.BooleanField(default=False, verbose_name='بازگشت داده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='books.book', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'امانت کتاب فیزیکی',
                'verbose_name_plural': 'امانت\u200cهای کتاب فیزیکی',
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalBookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_requests', to='books.book', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'درخواست کتاب فیزیکی',
                'verbose_name_plural': 'درخواست\u200cهای کتاب فیزیکی',
                'ordering': ['-created_at'],
            },
        ),
    ]
