# Generated by Django 5.2.8 on 2025-11-16 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_has_pdf_book_has_physical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام'),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='book',
            name='physical_count',
            field=models.IntegerField(default=0, verbose_name='تعداد کل نسخه فیزیکی'),
        ),
        migrations.AlterField(
            model_name='bookrequest',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='books.book'),
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تأیید شده')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.book', verbose_name='کتاب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='books.bookcomment', verbose_name='پاسخ به')),
            ],
            options={
                'verbose_name': 'نظر کتاب',
                'verbose_name_plural': 'نظرات کتاب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(verbose_name='IP کاربر')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='books.book', verbose_name='کتاب')),
            ],
            options={
                'verbose_name': 'امتیاز کتاب',
                'verbose_name_plural': 'امتیازات کتاب\u200cها',
                'unique_together': {('book', 'user_ip')},
            },
        ),
    ]
