# Generated by Django 5.2.8 on 2026-09-01 08:52

import json

from django.conf import settings
from django.db import migrations, models


def cleanup_legacy_mysql_placeholders(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "DELETE FROM books_book "
            "WHERE created_at = '0000-00-00 00:00:00.000000' "
            "AND updated_at = '0000-00-00 00:00:00.000000' "
            "AND translator = '[value-4]' AND publisher = '[value-5]'"
        )
        cursor.execute("UPDATE books_book SET category_id = NULL WHERE category_id = 0")


def migrate_tags_json(apps, schema_editor):
    Book = apps.get_model("books", "Book")
    for book in Book.objects.all().iterator(chunk_size=500):
        raw = (book.tags_json or "").strip()
        if not raw:
            tags = []
        else:
            try:
                parsed = json.loads(raw)
            except (TypeError, ValueError, json.JSONDecodeError):
                parsed = []
            tags = parsed if isinstance(parsed, list) else []
        book.tags = tags
        book.save(update_fields=["tags"])


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_bookrating_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(cleanup_legacy_mysql_placeholders, migrations.RunPython.noop),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='تگ‌ها'),
        ),
        migrations.RunPython(migrate_tags_json, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='book',
            name='tags_json',
        ),
        migrations.AlterField(
            model_name='book',
            name='request_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد درخواست'),
        ),
        migrations.AddIndex(
            model_name='bookrequest',
            index=models.Index(fields=['status', 'admin_read_at', '-created_at'], name='digital_req_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', '-created_at'], name='message_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalbookrequest',
            index=models.Index(fields=['status', 'admin_read_at', '-created_at'], name='physical_req_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='user_notification_idx'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('physical_available__lte', models.F('physical_count'))), name='book_available_not_above_total'),
        ),
        migrations.AddConstraint(
            model_name='bookrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected'])), name='digital_request_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='physicalbookborrow',
            constraint=models.CheckConstraint(condition=models.Q(('return_date__gte', models.F('borrow_date'))), name='borrow_return_not_before_borrow'),
        ),
        migrations.AddConstraint(
            model_name='physicalbookrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected'])), name='physical_request_valid_status'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
        migrations.AlterModelTable(
            name='bookcomment',
            table='book_comments',
        ),
        migrations.AlterModelTable(
            name='bookrating',
            table='book_ratings',
        ),
        migrations.AlterModelTable(
            name='bookrequest',
            table='digital_book_requests',
        ),
        migrations.AlterModelTable(
            name='category',
            table='book_categories',
        ),
        migrations.AlterModelTable(
            name='message',
            table='library_messages',
        ),
        migrations.AlterModelTable(
            name='physicalbookborrow',
            table='physical_book_borrows',
        ),
        migrations.AlterModelTable(
            name='physicalbookrequest',
            table='physical_book_requests',
        ),
        migrations.AlterModelTable(
            name='question',
            table='book_questions',
        ),
        migrations.AlterModelTable(
            name='usernotification',
            table='user_notifications',
        ),
    ]
