# Generated by Django 5.2.8 on 2026-09-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_private_pdf_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_url',
        ),
    ]
